/*
 * build-data.js
 * -----------------------------------------------------------------------------
 * WHAT THIS DOES:
 *   Reads the CSV you export from https://pokedata.ovh/events/ and converts it
 *   into a clean JavaScript file (data.js) that the website can read directly.
 *
 * WHY:
 *   The raw CSV uses semicolons, quotes, and a lot of columns we don't need.
 *   This script picks out just the useful fields, tidies them up, and writes
 *   them in a format the browser understands with zero extra setup.
 *
 * HOW TO USE (one command in the Terminal, from inside this folder):
 *   1. Export a fresh CSV from pokedata and save it here as "export_events.csv"
 *   2. Run:   node build-data.js
 *   3. Done — refresh the website and the new events appear.
 * -----------------------------------------------------------------------------
 */

const fs = require("fs"); // Node's built-in file reader/writer

// --- Settings -------------------------------------------------------------
const INPUT_FILE = "export_events.csv"; // the file you export from pokedata
const OUTPUT_FILE = "data.js"; // the file we generate for the website

// --- Step 1: read the raw CSV text ---------------------------------------
const raw = fs.readFileSync(INPUT_FILE, "utf8");

// Split into lines and drop any empty trailing lines.
const lines = raw.split(/\r?\n/).filter((line) => line.trim() !== "");

// The first line is the header row (column names). The rest are events.
const headerLine = lines[0];
const dataLines = lines.slice(1);

/*
 * Small helper: split ONE csv line into its fields.
 * pokedata uses ";" as the separator and wraps some values in "quotes"
 * (because addresses contain commas). This walks the line character by
 * character so a ";" inside quotes is NOT treated as a separator.
 */
function splitCsvLine(line) {
  const fields = [];
  let current = "";
  let insideQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      insideQuotes = !insideQuotes; // flip in/out of a quoted section
    } else if (char === ";" && !insideQuotes) {
      fields.push(current); // end of a field
      current = "";
    } else {
      current += char;
    }
  }
  fields.push(current); // push the final field
  return fields.map((f) => f.trim());
}

// Build a list of the column names so we can look fields up by name.
const headers = splitCsvLine(headerLine);

/*
 * Decide the "category" of an event from its pokedata type text.
 * This is what lets us separate Cups & Challenges from prereleases/friendlies.
 */
function categorize(typeText) {
  const t = (typeText || "").toLowerCase();
  if (t.includes("cup")) return "cup";
  if (t.includes("challenge")) return "challenge";
  if (t.includes("pre")) return "prerelease"; // "Pre Release"
  if (t.includes("friendly") || t.includes("league")) return "friendly";
  return "other";
}

// --- Step 2: turn each CSV row into a tidy event object ------------------
const events = dataLines.map((line) => {
  const fields = splitCsvLine(line);

  // Make a lookup like { type: "...", name: "...", date: "..." } by pairing
  // each header name with its value on this row.
  const row = {};
  headers.forEach((name, index) => {
    row[name] = fields[index] || "";
  });

  // "when" looks like "2026-06-28 12:00:00" — pull out the date and time.
  const whenParts = (row.when || "").split(" ");
  const date = whenParts[0] || row.date; // e.g. "2026-06-28"
  const time = whenParts[1] ? whenParts[1].slice(0, 5) : ""; // e.g. "12:00"

  // Build a Google Maps link from the shop + address (always works, easy to
  // navigate to). We use this as the click target for pokedata events.
  const mapQuery = encodeURIComponent(`${row.shop} ${row.street_adress}`);
  const mapsLink = `https://www.google.com/maps/search/?api=1&query=${mapQuery}`;

  return {
    category: categorize(row.type), // cup | challenge | prerelease | friendly
    typeLabel: row.type, // original text, e.g. "League Cup"
    name: row.name,
    shop: row.shop,
    address: row.street_adress,
    city: row.city,
    date: date, // "YYYY-MM-DD"
    time: time, // "HH:MM" (24h)
    link: mapsLink, // where clicking the event takes you
    source: "pokedata", // so we know where it came from
  };
});

// --- Step 3: write the events out as a JavaScript file -------------------
// We attach the list to "window" so the browser can read it with no server.
const output =
  "// AUTO-GENERATED by build-data.js — do not edit by hand.\n" +
  "// Re-run `node build-data.js` after exporting a new CSV from pokedata.\n" +
  "window.SANCTIONED_EVENTS = " +
  JSON.stringify(events, null, 2) +
  ";\n";

fs.writeFileSync(OUTPUT_FILE, output);

console.log(`✓ Converted ${events.length} events from ${INPUT_FILE} → ${OUTPUT_FILE}`);
